---
name: Create GitHub Release

permissions:
  contents: write

on: # yamllint disable-line rule:truthy
  push:
    tags:
      - "*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.11"

      - name: Install build dependencies
        run: python -m pip install --upgrade poetry

      - name: Build package
        run: python -m poetry build --version ${{ env.VERSION }} --dist-path dist

      - name: Extract version from tag
        id: extract_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> "$GITHUB_ENV"

      - name: Extract repository name
        run: echo "REPO_NAME=$(echo "${GITHUB_REPOSITORY#*/}" | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_ENV"

      - name: List dist contents
        run: ls -la .

      #- name: Create GitHub Release and Upload Artifacts
      #  uses: ncipollo/release-action@v1
      #  with:
      #    tag: ${{ github.ref }}
      #    name: Release ${{ env.VERSION }}
      #    artifacts: ./dist/${{ env.REPO_NAME }}-${{ env.VERSION }}-py3-none-any.whl,./dist/${{ env.REPO_NAME }}-${{ env.VERSION }}.tar.gz
      #    token: ${{ secrets.GITHUB_TOKEN }}
