name: Update version tag

permissions:
  contents: write

on:
  push:
    paths:
      - 'pyproject.toml'

jobs:
  update_version_tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install toml package
      run: pip install toml

    - name: Extract version from pyproject.toml
      run: |
        VERSION=$(python -c "import toml; print(toml.load('pyproject.toml')['tool']['poetry']['version'])")
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Configure Git user
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions@users.noreply.github.com"

    - name: Create and push tag
      run: |
        git tag -a "v${VERSION}" -m "Version ${VERSION}"
        git push origin "v${VERSION}"
